# Generated by Django 3.2 on 2022-10-03 09:55

from django.db import migrations, models
import django.db.models.deletion
import team.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=team.utils.CodeGenerator.generate_code, max_length=5, verbose_name='Код вступления в команду')),
                ('active_question', models.PositiveSmallIntegerField(default=0, verbose_name='Номер активного вопроса')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.game')),
            ],
        ),
    ]
