# Generated by Django 3.2 on 2022-10-06 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='name',
            field=models.CharField(default=2, max_length=255, verbose_name='Название команды'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='team',
            name='code',
            field=models.CharField(default='UP*HP', max_length=5, verbose_name='Код вступления в команду'),
        ),
    ]
