# Generated by Django 3.2 on 2022-10-07 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_auto_20221006_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='code',
            field=models.CharField(default='OV4)G', max_length=5, verbose_name='Код вступления в команду'),
        ),
    ]
