# Generated by Django 3.2 on 2022-10-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_alter_team_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='code',
            field=models.CharField(default='ZUV)I', max_length=5, verbose_name='Код вступления в команду'),
        ),
    ]
