# Generated by Django 3.2 on 2022-12-12 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_alter_team_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='code',
            field=models.CharField(default='N_58H', max_length=5, unique=True, verbose_name='Код вступления в команду'),
        ),
    ]
