# Generated by Django 3.2 on 2022-10-22 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_alter_team_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='code',
            field=models.CharField(default='_00OJ', max_length=5, unique=True, verbose_name='Код вступления в команду'),
        ),
    ]
