# Generated by Django 3.2 on 2022-10-31 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0009_auto_20221031_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='code',
            field=models.CharField(default='Z9OAN', max_length=5, unique=True, verbose_name='Код вступления в команду'),
        ),
        migrations.AlterField(
            model_name='team',
            name='timer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='team', to='team.timer'),
        ),
    ]
