# Generated by Django 3.2 on 2022-11-01 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0010_auto_20221031_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='code',
            field=models.CharField(default='KLHM.', max_length=5, unique=True, verbose_name='Код вступления в команду'),
        ),
        migrations.AlterField(
            model_name='team',
            name='timer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team', to='team.timer'),
        ),
        migrations.AlterField(
            model_name='timer',
            name='start_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Время отсчёта таймера вопроса'),
        ),
    ]
