# Generated by Django 3.2 on 2022-11-02 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0011_auto_20221101_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='code',
            field=models.CharField(default='36SVO', max_length=5, unique=True, verbose_name='Код вступления в команду'),
        ),
    ]
