# Generated by Django 3.2 on 2022-11-05 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0014_auto_20221104_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='code',
            field=models.CharField(default='SN1M1', max_length=5, unique=True, verbose_name='Код вступления в команду'),
        ),
    ]
