# Generated by Django 3.2 on 2022-11-05 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0015_alter_team_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='code',
            field=models.CharField(default='10YL8', max_length=5, unique=True, verbose_name='Код вступления в команду'),
        ),
    ]
