# Generated by Django 3.2 on 2022-11-15 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0018_alter_team_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='code',
            field=models.CharField(default='SBJR3', max_length=5, unique=True, verbose_name='Код вступления в команду'),
        ),
    ]
