# Generated by Django 3.2 on 2022-11-19 12:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('users_in_team_lim', models.PositiveSmallIntegerField(default=0, verbose_name='Предел человек в команде')),
                ('question_time', models.TimeField(verbose_name='Время на один вопрос')),
                ('game_state', models.CharField(choices=[('ON', 'Game is on'), ('OFF', 'Game is off')], default='OFF', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('correct_answers', models.JSONField(default=list, verbose_name='Правильные ответы на вопрос')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.game')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LeaderBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата начала игры')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания игры')),
                ('already_end', models.BooleanField(default=False, verbose_name='Игра окончена')),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leader_boards', to='game.game')),
            ],
        ),
        migrations.CreateModel(
            name='FinishTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finish_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время финиша команды')),
                ('bonus_points', models.PositiveIntegerField(default=0, verbose_name='Бонусные баллы')),
                ('leader_board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.leaderboard')),
            ],
        ),
    ]
