# Generated by Django 3.2 on 2022-10-03 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users_in_team_lim', models.PositiveSmallIntegerField(default=0, verbose_name='Предел человек в команде')),
                ('question_time', models.TimeField(verbose_name='Время на один вопрос')),
                ('game_state', models.CharField(choices=[('ON', 'Game is on'), ('OFF', 'Game is off')], default='OFF', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('order', models.PositiveSmallIntegerField()),
                ('correct_answers', models.JSONField(default=dict, verbose_name='Правильные ответы на вопрос')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.game')),
            ],
        ),
    ]
