# Generated by Django 3.2 on 2022-10-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='name',
            field=models.CharField(default=2, max_length=255, verbose_name='Имя'),
            preserve_default=False,
        ),
    ]
