# Generated by Django 3.2 on 2022-10-07 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_game_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('order',)},
        ),
    ]
