# Generated by Django 3.2 on 2022-12-03 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_finishteam_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='users_in_team_lim',
        ),
    ]
