# Generated by Django 3.2 on 2022-12-12 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_remove_game_users_in_team_lim'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('default', 'default type of question'), ('blitz', 'blitz type of question')], default='default', max_length=50, verbose_name='Тип вопроса'),
        ),
    ]
