# Generated by Django 3.2 on 2022-10-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_question_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_answers',
            field=models.JSONField(default=list, verbose_name='Правильные ответы на вопрос'),
        ),
    ]
