# Generated by Django 3.2 on 2022-10-13 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_question_correct_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
