# Generated by Django 3.2 on 2022-10-31 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_question_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={},
        ),
    ]
