# Generated by Django 3.2 on 2022-11-03 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_alter_question_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время начала игры'),
        ),
    ]
