# Generated by Django 3.2 on 2022-11-04 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0014_auto_20221104_1251'),
        ('game', '0007_game_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now=True, verbose_name='Дата начала игры')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания игры')),
                ('already_end', models.BooleanField(default=False, verbose_name='Игра окончена')),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.game')),
            ],
        ),
        migrations.CreateModel(
            name='FinishTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finish_date', models.DateTimeField(auto_now=True, verbose_name='Дата и время финиша команды')),
                ('bonus_points', models.PositiveIntegerField(default=0, verbose_name='Бонусные баллы')),
                ('leader_board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.leaderboard')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='team.team')),
            ],
        ),
    ]
