# Generated by Django 3.2 on 2022-11-05 06:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_auto_20221105_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finishteam',
            name='finish_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время финиша команды'),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата начала игры'),
        ),
    ]
