# Generated by Django 3.2 on 2022-11-15 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_auto_20221105_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='start_time',
        ),
    ]
